name: 'Update Notion Page properties'
description: 'Updata properties in notion page'
inputs:
  notion-token:
    description: 'Notion API Key'
    required: true
  page-id: 
    description: 'Notion page id to be updated'
    required: true
outputs:
  status:
    description: 'Update status'
runs:
  using: 'node16'
  main: 'index.js'
